services:
  alxtravelapp:
    image: alxtravelapp
    container_name: alx_travel_app
    command: |
     sh -c "
      echo 'Waiting for MySQL...';
      sleep 10;
      python manage.py makemigrations &&
      python manage.py migrate
      python manage.py runserver 0.0.0.0:8000
      "
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db


  db:
    image: mysql:latest
    container_name: alx_travel_app_db
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: travel_app_db
      MYSQL_USER: alx_user
      MYSQL_PASSWORD: alx_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
